# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: City of Austin Design, Technology, and Innovation Fellows
email: innovationfellows@austintexas.gov
description: >
  The City of Austin’s Design, Technology, and Innovation Fellows program provides 
  an opportunity for Austin’s passionate and civic-minded designers and developers to bring the 
  principles, values, and practices of the technology sector into government.
url: "https://cityofaustin.github.io/innovation-fellows" # the base hostname & protocol for your site
twitter_username: civiqueso
github_username:  cityofaustin
medium_url: https://medium.com/city-of-austin-design-technology-innovation

# Build settings
markdown: kramdown
collections:
  - blog_summaries
  - project_summaries
  - staff_bios
  
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  
# Jekyll SEO Tag
# See https://github.com/jekyll/jekyll-seo-tag
twitter:
  username: civiqueso
logo: /img/dti-fellows-logo.png
